FROM stimela/meqtrees:1.2.0
RUN docker-apt-install python3-pip \
                       python3-numpy
#RUN pip3 install --upgrade aimfast
RUN pip3 install --upgrade https://github.com/Athanaseus/aimfast.git@Prepare_major_release
