FROM stimela/base:1.6.0
MAINTAINER <sphemakh@gmail.com>
RUN docker-apt-install python3-casacore \
    casacore-dev \
    libcfitsio-dev \
    wcslib-dev
RUN pip install git+https://github.com/ratt-ru/shadeMS.git@v0.4.0
RUN pip install -I numpy scabha
RUN shadems -h
