#!/usr/bin/env bash
set -e
set -u
export INPUT=/scratch/input
export OUTPUT=/scratch/output
export CONFIG=/scratch/configfile
export MSDIR=/scratch/msdir
python /scratch/code/run.py 2>&1 | tee -a /scratch/logfile
(exit ${PIPESTATUS[0]})
