#!/usr/bin/env bash
set -e
set -u
echo "STARTED XVFB"
/etc/init.d/xvfb start || echo "Virtual frame buffer not installed. You may not be able to plot with this cab"
echo "HELLO!!!"
#python /scratch/code/run.py #> $LOGFILE 2>&1
EXIT_STAT=${PIPESTATUS[0]}
/etc/init.d/xvfb stop || echo ""
exit $EXIT_STAT
