FROM stimela/base:0.2.3
MAINTAINER <sphemakh@gmail.com>
RUN docker-apt-install meqtrees-timba \
    python-casacore \
    python-owlcat
RUN pip install git+https://github.com/SpheMakh/msutils
RUN pip install pyyaml
