FROM stimela/base
MAINTAINER <sphemakh@gmail.com>
RUN docker-apt-install meqtrees-timba \
    python-casacore \
    python-owlcat
RUN git clone https://github.com/SpheMakh/msutils
RUN pip install /msutils


