# This workflow will install Python dependencies and create a PR to caracal-pipeline after a successful version release
name: Python Dependants

# Only trigger, when the publish workflow succeeded
#on:
#  workflow_run:
#    workflows: ["Upload Python Package"]
#    types:
#      - completed
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POETRY_VERSION: 1.7.1

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache Installations
      id: cache-installs
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: install-${{ env.INSTALL_CACHE_HASH }}-3
    - name: Install Poetry
      if: steps.cache-installs.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version ${{ env.POETRY_VERSION }}
    - name: Test poetry
      run: poetry --version
    - name: Git clone caracal
      run: git clone https://github.com/caracal-pipeline/caracal.git ../caracal/
    - uses: actions/checkout@v4
    - name: Make changes to pull request
      run: |
       cd ../caracal/
       poetry add stimela@latest --lock
       git add poetry.lock pyproject.toml
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: deps101
        base: ${{ github.head_ref }}
        delete-branch: true
        title: 'Stimela dependency update'
        body: |
          Update report
          - Auto-generated by stimela-classic
        labels: |
          automated pr
        assignees: athanaseus
        reviewers: sphemakh
        draft: false
